import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";
import { jsPDF } from "https://cdn.jsdelivr.net/npm/jspdf@2.5.1/+esm";

const firebaseConfig={apiKey:"AIzaSyD9LW4cEV6NPC5wi7Zxrj6UKu0FeSUJZCI",authDomain:"oasis-visit-card.firebaseapp.com",projectId:"oasis-visit-card",storageBucket:"oasis-visit-card.firebasestorage.app",messagingSenderId:"6930140490",appId:"1:6930140490:web:66fb3902d8cfe93e4085b3"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),provider=new GoogleAuthProvider(),db=getFirestore(app),storage=getStorage(app);
let user=null,clients=[],equipment=[],diagnostics=[],settings={businessName:"Oasis Air Cleaner Services LLC",businessPhone:"787-664-3079",businessEmail:"",businessAddress:"",logoUrl:""};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[<>&"']/g,s=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&#039;"}[s]));
const clean=v=>String(v||"archivo").replace(/[^\w\-]+/g,"_").slice(0,50);

$("loginBtn").onclick=()=>signInWithPopup(auth,provider).catch(e=>alert(e.message));
$("logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{user=u;$("authScreen").classList.toggle("hidden",!!u);$("app").classList.toggle("hidden",!u);if(u)await boot()});

async function boot(){bind();await loadSettings();setupNextVisit();await loadAll();}
function bind(){
 document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
 $("goSearchBtn").onclick=()=>showPage("searchPage");$("goDiagnosticBtn").onclick=()=>showPage("diagnosticPage");
 $("newClientBtn").onclick=()=>openClient();$("clientFromDiagBtn").onclick=()=>openClient();
 $("settingsBtn").onclick=()=>$("settingsDialog").showModal();
 document.querySelectorAll(".close-client").forEach(b=>b.onclick=()=>$("clientDialog").close());
 document.querySelectorAll(".close-settings").forEach(b=>b.onclick=()=>$("settingsDialog").close());
 $("searchInput").oninput=renderSearch;
 $("clientSelect").onchange=fillEquipmentSelect;$("equipmentSelect").onchange=fillEquipmentFields;
 ["cooling","pressure","drain","evaporator","condenser"].forEach(n=>$("diagnosticForm")[n].oninput=updateScore);
 $("cancelEditBtn").onclick=clearForm;
}
function showPage(id){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===id));document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active")}

async function loadAll(){clients=await col("clients");equipment=await col("equipment");diagnostics=await col("diagnostics");render();}
async function col(n){const s=await getDocs(collection(db,"users",user.uid,n));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadSettings(){const s=await getDoc(doc(db,"users",user.uid,"settings","main"));if(s.exists())settings={...settings,...s.data()};const f=$("settingsForm");f.businessName.value=settings.businessName||"";f.businessPhone.value=settings.businessPhone||"";f.businessEmail.value=settings.businessEmail||"";f.businessAddress.value=settings.businessAddress||""}

$("settingsForm").onsubmit=async e=>{e.preventDefault();const f=e.target;let logoUrl=settings.logoUrl||"";if($("logoFile").files[0]){const r=ref(storage,`users/${user.uid}/settings/logo_${Date.now()}`);await uploadBytes(r,$("logoFile").files[0]);logoUrl=await getDownloadURL(r)}settings={businessName:f.businessName.value,businessPhone:f.businessPhone.value,businessEmail:f.businessEmail.value,businessAddress:f.businessAddress.value,logoUrl};await setDoc(doc(db,"users",user.uid,"settings","main"),settings,{merge:true});$("settingsDialog").close()};

function render(){renderKpis();renderAgenda();renderSearch();renderSelects()}
const clientEq=id=>equipment.filter(e=>e.clientId===id), clientDiag=id=>diagnostics.filter(d=>d.clientId===id), eqDiag=id=>diagnostics.filter(d=>d.equipmentId===id);
function avg(arr){const s=arr.map(x=>Number(x.healthScore||0)).filter(Boolean);return s.length?Math.round(s.reduce((a,b)=>a+b,0)/s.length):0}
function cond(score){score=Number(score||0);if(score>=82)return{txt:"Excelente",cls:"ok"};if(score>=62)return{txt:"Bueno / Preventivo",cls:"warn"};return{txt:"Requiere atención",cls:"danger"}}
function renderKpis(){$("kpiClients").textContent=clients.length;$("kpiEquipment").textContent=equipment.length;const now=new Date();$("kpiMonth").textContent=diagnostics.filter(d=>(d.createdAtText||"").includes(String(now.getFullYear()))).length}
function renderAgenda(){const agenda=$("agendaList"),watch=$("watchList");agenda.innerHTML="";watch.innerHTML="";equipment.filter(e=>e.nextVisit).sort((a,b)=>String(a.nextVisit).localeCompare(String(b.nextVisit))).slice(0,8).forEach(e=>{const c=clients.find(x=>x.id===e.clientId)||{};agenda.innerHTML+=`<div class="compact-item"><strong>${esc(e.nextVisit)} · ${esc(e.area||"Equipo")}</strong><span>${esc(c.name||"")} · ${esc(e.brand||"")}</span></div>`});equipment.filter(e=>Number(e.healthScore||0)<75).slice(0,8).forEach(e=>{const c=clients.find(x=>x.id===e.clientId)||{},st=cond(e.healthScore);watch.innerHTML+=`<div class="compact-item"><strong>${esc(e.area||"Equipo")} <span class="${st.cls}">${st.txt}</span></strong><span>${esc(c.name||"")} · índice interno ${e.healthScore||"—"}</span></div>`});if(!agenda.innerHTML)agenda.innerHTML=`<div class="compact-item"><strong>Sin visitas próximas</strong><span>No hay seguimientos pendientes.</span></div>`;if(!watch.innerHTML)watch.innerHTML=`<div class="compact-item"><strong>Sin alertas</strong><span>Equipos sin observaciones críticas.</span></div>`}

function renderSearch(){const q=($("searchInput").value||"").toLowerCase(),box=$("searchResults");box.innerHTML="";if(!q){box.innerHTML=`<div class="compact-item"><strong>Busca un cliente para abrir su expediente.</strong><span>Los expedientes permanecen ocultos hasta que se necesitan.</span></div>`;return}clients.filter(c=>JSON.stringify(c).toLowerCase().includes(q)).forEach(c=>{const row=document.createElement("div");row.className="result-row";row.innerHTML=`<div><strong>${esc(c.name)}</strong><p>${esc(c.phone||"")} · ${esc(c.address||"")}</p></div><button class="small-btn">Abrir expediente</button>`;row.querySelector("button").onclick=()=>openRecord(c.id);box.appendChild(row)})}

function openRecord(id){const c=clients.find(x=>x.id===id),eqs=clientEq(id),ds=clientDiag(id);showPage("recordPage");$("recordView").innerHTML=`<div class="record-header"><div><span class="kicker">EXPEDIENTE TÉCNICO HVAC</span><h2>${esc(c.name)}</h2><p>${esc(c.phone||"")} · ${esc(c.address||"")}</p></div><div class="top-actions"><button class="primary-btn" id="pdfBtn">Generar PDF</button><button class="ghost-btn" id="diagBtn">Nuevo diagnóstico</button></div></div><div class="record-grid"><article class="panel"><h3>Equipos</h3><div class="equipment-list">${eqs.map(e=>eqRow(e)).join("")||"Sin equipos registrados."}</div></article><article class="panel"><h3>Historial técnico</h3><div class="timeline">${ds.map(d=>timeRow(d)).join("")||"Sin historial."}</div></article></div>`;$("pdfBtn").onclick=()=>pdfRecord(id);$("diagBtn").onclick=()=>{showPage("diagnosticPage");$("clientSelect").value=id;fillEquipmentSelect()}}
function eqRow(e){const st=cond(e.healthScore);return`<div class="equipment-row"><strong>${esc(e.area||"Equipo")}</strong><p>${esc([e.brand,e.model,e.btu].filter(Boolean).join(" · "))}</p><p>Condición: <span class="${st.cls} status">${st.txt}</span></p><p>Próxima visita: ${esc(e.nextVisit||"Por coordinar")}</p></div>`}
function timeRow(d){const e=equipment.find(x=>x.id===d.equipmentId)||{},st=cond(d.healthScore);return`<div class="timeline-row"><strong>${esc(d.createdAtText||"")} · ${esc(e.area||"Equipo")}</strong><p>${esc(d.serviceType||"Servicio")} · <span class="${st.cls}">${st.txt}</span></p><p>${esc(d.notes||"")}</p></div>`}

function renderSelects(){$("clientSelect").innerHTML=`<option value="">Selecciona cliente</option>`+clients.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.phone||"")}</option>`).join("");fillEquipmentSelect()}
function fillEquipmentSelect(){const id=$("clientSelect").value;const eqs=equipment.filter(e=>!id||e.clientId===id);$("equipmentSelect").innerHTML=`<option value="">Nuevo equipo</option>`+eqs.map(e=>`<option value="${e.id}">${esc(e.area)} · ${esc(e.brand||"")}</option>`).join("")}
function fillEquipmentFields(){const e=equipment.find(x=>x.id===$("equipmentSelect").value);if(!e)return;const f=$("diagnosticForm");f.area.value=e.area||"";f.brand.value=e.brand||"";f.model.value=e.model||"";f.btu.value=e.btu||"";f.internalId.value=e.internalId||""}

function openClient(c=null){const f=$("clientForm");f.clientId.value=c?.id||"";f.name.value=c?.name||"";f.phone.value=c?.phone||"";f.address.value=c?.address||"";$("clientDialog").showModal()}
$("clientForm").onsubmit=async e=>{e.preventDefault();const f=e.target,data={name:f.name.value,phone:f.phone.value,address:f.address.value,updatedAt:serverTimestamp()};if(f.clientId.value)await updateDoc(doc(db,"users",user.uid,"clients",f.clientId.value),data);else await addDoc(collection(db,"users",user.uid,"clients"),{...data,createdAt:serverTimestamp()});$("clientDialog").close();await loadAll()}

function setupNextVisit(){const i=$("visitInterval"),n=$("nextVisit");const apply=()=>{if(i.value==="custom")return;const d=new Date();d.setMonth(d.getMonth()+Number(i.value||6));n.value=d.toISOString().slice(0,10)};i.onchange=apply;apply()}
function updateScore(){const f=$("diagnosticForm"),names=["cooling","pressure","drain","evaporator","condenser"];$("scorePreview").textContent=Math.round(names.reduce((s,n)=>s+Number(f[n].value||0),0)/names.length)}
const score=()=>Number($("scorePreview").textContent||85);
async function upload(files,folder){const urls=[];for(const file of Array.from(files||[])){const r=ref(storage,`users/${user.uid}/${folder}/${Date.now()}_${file.name.replace(/[^\w.\-]+/g,"_")}`);await uploadBytes(r,file);urls.push(await getDownloadURL(r))}return urls}
$("diagnosticForm").onsubmit=async e=>{e.preventDefault();const f=e.target;if(!f.clientId.value)return alert("Selecciona cliente.");let eid=f.equipmentId.value;const healthScore=score();const eq={clientId:f.clientId.value,area:f.area.value||"Equipo",brand:f.brand.value,model:f.model.value,btu:f.btu.value,internalId:f.internalId.value,healthScore,nextVisit:f.nextVisit.value,updatedAt:serverTimestamp()};if(eid)await updateDoc(doc(db,"users",user.uid,"equipment",eid),eq);else{const r=await addDoc(collection(db,"users",user.uid,"equipment"),{...eq,createdAt:serverTimestamp()});eid=r.id}const diag={clientId:f.clientId.value,equipmentId:eid,serviceType:f.serviceType.value,technician:f.technician.value,visitInterval:f.visitInterval.value,visitIntervalLabel:f.visitInterval.selectedOptions[0].textContent,nextVisit:f.nextVisit.value,nextVisitReason:f.nextVisitReason.value,healthScore,notes:f.notes.value,recommendations:f.recommendations.value,beforeUrls:await upload($("beforePhotos").files,"before"),afterUrls:await upload($("afterPhotos").files,"after"),createdAtText:new Date().toLocaleDateString("es-PR"),createdAt:serverTimestamp()};await addDoc(collection(db,"users",user.uid,"diagnostics"),diag);clearForm();await loadAll();openRecord(f.clientId.value)}
function clearForm(){$("diagnosticForm").reset();$("scorePreview").textContent=85;setupNextVisit();$("beforePhotos").value="";$("afterPhotos").value=""}

async function pdfRecord(id){const c=clients.find(x=>x.id===id),eqs=clientEq(id),ds=clientDiag(id),pdf=new jsPDF({unit:"pt",format:"letter"}),W=pdf.internal.pageSize.getWidth(),m=54;let y=60;pdf.setTextColor(20,20,20);pdf.setFont("helvetica","bold");pdf.setFontSize(13);pdf.text((settings.businessName||"Oasis Air Cleaner Services LLC").toUpperCase(),m,y);y+=34;pdf.setFontSize(22);pdf.text("EXPEDIENTE TÉCNICO HVAC",m,y);y+=28;pdf.setFont("helvetica","normal");pdf.setFontSize(10);pdf.text(`Cliente: ${c.name||""}`,m,y);y+=16;pdf.text(`Propiedad: ${c.address||""}`,m,y);y+=16;pdf.text(`Teléfono: ${c.phone||""}`,m,y);y+=16;pdf.text(`Fecha: ${new Date().toLocaleDateString("es-PR")}`,m,y);y+=30;line(pdf,W,m,y);y+=28;section(pdf,"RESUMEN GENERAL",m,y);y+=22;pdf.setFont("helvetica","normal");pdf.text(`Cantidad de equipos inspeccionados: ${eqs.length}`,m,y);y+=16;pdf.text(`Cantidad de servicios registrados: ${ds.length}`,m,y);y+=16;pdf.text(`Próxima visita recomendada: ${nextDate(eqs)}`,m,y);y+=34;section(pdf,"EQUIPOS",m,y);y+=22;for(const e of eqs){if(y>700){pdf.addPage();y=60}const st=cond(e.healthScore);pdf.setFont("helvetica","bold");pdf.text(String(e.area||"Equipo").toUpperCase(),m,y);y+=16;pdf.setFont("helvetica","normal");pdf.text(`Marca / modelo / capacidad: ${[e.brand,e.model,e.btu].filter(Boolean).join(" · ")||"No especificado"}`,m,y);y+=16;pdf.text(`Condición: ${st.txt}`,m,y);y+=16;pdf.text(`Próxima visita: ${e.nextVisit||"Por coordinar"}`,m,y);y+=24}section(pdf,"HISTORIAL DE SERVICIOS",m,y);y+=22;for(const d of ds){if(y>720){pdf.addPage();y=60}const e=equipment.find(x=>x.id===d.equipmentId)||{};pdf.setFont("helvetica","bold");pdf.text(`${d.createdAtText||""} · ${e.area||"Equipo"}`,m,y);y+=15;pdf.setFont("helvetica","normal");pdf.text(`${d.serviceType||""} · Técnico: ${d.technician||"—"}`,m,y);y+=15;if(d.notes){pdf.text(pdf.splitTextToSize(`Observaciones: ${d.notes}`,W-(m*2)),m,y);y+=30}y+=8}y=Math.max(y,690);line(pdf,W,m,y);y+=18;pdf.setFontSize(9);pdf.text(`${settings.businessName||""} · ${settings.businessPhone||""} · ${settings.businessEmail||""}`,m,y);const blob=pdf.output("blob");const file=new File([blob],`Expediente-Tecnico-${clean(c.name)}.pdf`,{type:"application/pdf"});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:"Expediente Técnico HVAC",text:"Expediente técnico",files:[file]});return}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function section(pdf,t,x,y){pdf.setFont("helvetica","bold");pdf.setFontSize(11);pdf.text(t,x,y)}
function line(pdf,W,m,y){pdf.setDrawColor(180,180,180);pdf.line(m,y,W-m,y)}
function nextDate(eqs){return eqs.map(e=>e.nextVisit).filter(Boolean).sort()[0]||"Por coordinar"}
